workflows:
  sample-workflow:
    name: Schedule an automation test with Sofy
    environment:
      vars:
        SOFY_API_KEY: 1027B480-00D9-45EF-8D14-D728E0DE70F7
    scripts:
      - name: Schedule an automation test with Sofy
        script: |
          curl --location --request POST 'https://api.sofy.ai/api/CICD/ScheduleAutomatedTestRun' \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "APIKey": $SOFY_API_KEY,
              "ScheduledID": 2612
            }'
